name: Windows

on:
  - push

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Install clang-format
      run: |
        choco install llvm -y
        echo "::add-path::C:\\Program Files\\LLVM\\bin"

    - name: Configure
      run: cmake -Htest -Bbuild

    - name: Run format
      run: "cmake --build build --target format"

    - name: Check format
      shell: powershell
      run: "-not (cmake --build build --target check-format)"

    - name: Fix format
      run: cmake --build build --target fix-format

    - name: Check fixed format
      shell: powershell
      run: cmake --build build --target check-format -and (-not (git diff --exit-code))