name: Windows

on:
  - push

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Install clang-format
      run: |
        choco install llvm -y
        echo "::add-path::C:\\Program Files\\LLVM\\bin"

    - name: Configure
      run: cmake -Htest -Bbuild

    - name: Run format
      run: "cmake --build build --target format"

    - name: Check format
      shell: powershell
      run: |
        function Get-ExitBoolean($cmd) { & $cmd | Out-Null; $? }
        -not (Get-ExitBoolean (cmake --build build --target check-format))

    - name: Fix format
      run: cmake --build build --target fix-format

    - name: Check fixed format
      shell: powershell
      run: |
        function Get-ExitBoolean($cmd) { & $cmd | Out-Null; $? }
        (Get-ExitBoolean (cmake --build build --target check-format)) -and (-not (Get-ExitBoolean (git diff --exit-code)))